version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nvgpu-exporter
    binary: nvgpu-exporter
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: [ 'binary' ]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mlmon
    name: nvgpu-exporter