apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvgpu-exporter
  namespace: monitoring
  labels:
    app: nvgpu-exporter
    app.kubernetes.io/name: nvgpu-exporter
    app.kubernetes.io/instance: nvgpu-exporter
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    matchLabels:
      app: nvgpu-exporter
      app.kubernetes.io/name: nvgpu-exporter
      app.kubernetes.io/instance: nvgpu-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nvgpu-exporter
        app.kubernetes.io/name: nvgpu-exporter
        app.kubernetes.io/instance: nvgpu-exporter
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: exporter
        app.kubernetes.io/part-of: monitoring
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoExecute"
        - key: kubernetes.io/arch
          operator: Exists
          effect: NoSchedule
      runtimeClassName: nvidia
      hostPID: false
      containers:
        - name: nvml
          image: ghcr.io/mlmon/nvgpu-exporter/nvgpu-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: dev
              mountPath: /dev
            # Sysfs paths used by the driver stack
            - name: sys
              mountPath: /sys
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
