apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvml-access
  namespace: monitoring
  labels:
    app: nvml-access
spec:
  selector:
    matchLabels:
      app: nvml-access
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nvml-access
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoExecute"
        - key: kubernetes.io/arch
          operator: Exists
          effect: NoSchedule
      runtimeClassName: nvidia
      hostPID: false
      containers:
        - name: nvml
          image: ghcr.io/mlmon/nvgpu-exporter/nvgpu-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: dev
              mountPath: /dev
            # Sysfs paths used by the driver stack
            - name: sys
              mountPath: /sys
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
